### ISSUE TITLE
Summary: Final Issues for Hotfix Three Release

### ISSUE THREAD

**Issue by Dizzy611** [Insidious611/DancingMadFF6#88]
This bug is a summary of the final issues/steps needed for a Hotfix Three release. This includes some minor bugs not listed elsewhere.

- [x] Test changed UI elements with scaling set to "Application" on laptop (high DPI display) (#87) -- *DONE*, fixes applied to make installer at least usable without changing scaling settings.
- [x] Test changed UI elements with scaling set to "Application" on desktop (normal DPI 1080p display) (#87) -- *DONE*, works fine still.
- [x] Fix total size of current download 'sticking' when a download is skipped. (Unique issue) -- *DONE*, skipped files now don't end up in the "Downloading..." status branch at all, and should thus not set "size".
- [x] Find a way to better notify the user that a file is being skipped because it's already been downloaded and the MD5sums match (currently just shows 'downloading' and then skips to the next track) (Unique issue) -- *DONE*, installer now shows that existing files are being checksummed.
- [x] Fix Amazon server (#84) -- *DONE*, the main issue seems to be a misunderstanding on my part of how S3 buckets work, but just in case I made sure that the files are all publically available anyway. A change was made to the "mirror check" to make it work with Amazon.
- [x] Look through Readme, add entries for new features. Update list of currently known bugs. -- *DONE*, Readme edited, section for new features and bug fixes added and populated, section for known bugs updated. Credits amended.
- [x] Test install with multiple selections (custom selection with "Recommended" preset loaded and More Friends opera selected tested) -- *DONE*, now tested with FFT and OST selections. Others should be fine as it's just a matter of what gets downloaded.
- [x] Basic test of FF3 with Dancing Mad installed to check for regressions. -- *DONE*, tested to the first boss.
- [x] Fix minor inconsistencies with installer (such as self-extractor listing an old release date) (Unique issue) -- *DONE*, the self-extractor was the only minor inconsistency I could find and has been fixed.
- [x] Update version of TWUE on server to 2.01 -- *DONE*, TWUE 2.01 is now the version uploaded as "contrib/twue.ips" on the server.
- [x] Make sure all mirrors are synced. -- *DONE*, all three current mirrors should now be synchronized.
- [x] Fix lack of "SPC" option for Opera (pointed out by edale2) -- *DONE*, there is now an SPC option for the Opera.
- [x] Write qhimm/rhdn release posts.
- [x] Write release announcement for qhimm/Dancing Mad discord servers.
- [x] Build release. -- *DONE*, the installer is now provisionally built and ready for publishing, unless remaining testing shows any last minute bugs.
- [x] Publish release.

**Comment by Dizzy611** [comment]
Updating list for fixes/completed tests from 489ceed206d2439363676ce908233e0f485e2b59

**Comment by Dizzy611** [comment]
Updating list for readme fixes from 176bd71602a367c6ff69e95b2594bbccabdabf82
